name: Makefile CI

on:
  push:
      tags:
        - '*'

jobs:
  deploy-linux:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2


    - name: python-tk
      run: |
          sudo apt-get update
          sudo apt-get remove python3
          sudo apt-get install tk
          sudo apt-get install python3
          sudo apt-get install python3-venv
          sudo apt-get install python3-tk

    - name: Install dependencies
      run: make -C build-linux venv_
      
    - name: Run build
      run: make -C build-linux all
      
    - name: Update Releases
      uses: ncipollo/release-action@v1.9.0
      with:
        allowUpdates: true
        artifacts: publish-linux/LS_LINUX.zip, publish-linux/Updater_Linux
        name: Latest executables
        tag: Latest

    - name: New Release
      uses: ncipollo/release-action@v1.9.0
      with:
        allowUpdates: true
        artifacts: publish-linux/LS_LINUX.zip, publish-linux/Updater_Linux

  deploy-win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: make -C build-win venv_
      
    - name: Run build
      run: make -C build-win all
      
    - name: Update Releases
      uses: ncipollo/release-action@v1.9.0
      with:
        allowUpdates: true
        artifacts: publish-win/LS_WINDOWS.zip, publish-win/Updater_Windows.exe
        name: Latest executables
        tag: Latest

    - name: New Release
      uses: ncipollo/release-action@v1.9.0
      with:
        allowUpdates: true
        artifacts: publish-win/LS_WINDOWS.zip, publish-win/Updater_Windows.exe


  deploy-mac:

    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: make -C build-mac venv_

      - name: Run build
        run: make -C build-mac all

      - name: Update Releases
        uses: ncipollo/release-action@v1.9.0
        with:
          allowUpdates: true
          artifacts: publish-mac/LS_MACOS.zip, publish-mac/Updater_MacOs
          name: Latest executables
          tag: Latest

      - name: New Release
        uses: ncipollo/release-action@v1.9.0
        with:
          allowUpdates: true
          artifacts: publish-mac/LS_MACOS.zip, publish-mac/Updater_MacOs
