name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    
    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make -m=build-linux venv_
      
    - name: Run build
      run: make -m=build-linux all
      
    - name: Upload new Release
      uses: ncipollo/release-action@v1.9.0
      with:
        allowUpdates: true
        artifact: publish-linux/LS_LINUX.zip, publish-linux/updater_Linux
