name: Makefile CI

on:
  push:
      tags:
        - '*'

jobs:
  create-new-release:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Create Source Zip
        run: |
            mkdir -p release
            zip release/LS_PYTHON.zip -r app *.py *.md
            cp Update.py release/Updater_Python.py

      - name: New Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true
          makeLatest: true
          artifacts: release/LS_PYTHON.zip, release/Updater_Python.py

  deploy-linux:
    needs: create-new-release
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: python-tk
      run: |
          sudo apt-get update
          sudo apt-get install tk
          sudo apt-get install --upgrade python3
          sudo apt-get install python3-venv
          sudo apt-get install python3-tk

    - name: Install dependencies
      run: make -C build-linux venv_
      
    - name: Run build
      run: make -C build-linux all

    - name: Add to New Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        omitBodyDuringUpdate: true
        artifacts: publish-linux/LS_LINUX.zip, publish-linux/Updater_Linux

  deploy-win:
    needs: create-new-release
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: make -C build-win venv_
      
    - name: Run build
      run: make -C build-win all

    - name: Add to New Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        omitBodyDuringUpdate: true
        artifacts: publish-win/LS_WINDOWS.zip, publish-win/Updater_Windows.exe

  deploy-mac:
    needs: create-new-release
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: make -C build-mac venv_

      - name: Run build
        run: make -C build-mac all

      - name: Add to New Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBodyDuringUpdate: true
          artifacts: publish-mac/LS_MACOS.zip, publish-mac/Updater_MacOs
