name: Makefile CI

on:
  push:
      tags:
        - '*'

jobs:
  deploy-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: make -C build-linux venv_
      
    - name: Run build
      run: make -C build-linux all
      
    - name: Update Releases
      uses: ncipollo/release-action@v1.9.0
      with:
        allowUpdates: true
        artifacts: publish-linux/LS_LINUX.zip, publish-linux/Updater_Linux
        name: Latest executables
        tag: Latest
    
    - name: New Release
      uses: ncipollo/release-action@v1.9.0
      with:
        artifacts: publish-linux/LS_LINUX.zip, publish-linux/Updater_Linux
  
  deploy-win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: make -C build-win venv_
      
    - name: Run build
      run: make -C build-win all
      
    - name: Update Releases
      uses: ncipollo/release-action@v1.9.0
      with:
        allowUpdates: true
        artifacts: publish-win/LS_WINDOWS.zip, publish-win/Updater_Windows.exe
        name: Latest executables
        tag: Latest
        
    - name: New Release
      uses: ncipollo/release-action@v1.9.0
      with:
        artifacts: publish-win/LS_WINDOWS.zip, publish-win/Updater_Windows.exe
